# Generated by Django 6.1 on 2026-08-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('badge_code', models.CharField(max_length=100, verbose_name='Nishon kodi')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Erishilgan vaqti')),
            ],
            options={
                'verbose_name': 'Nishon/Yutuq',
                'verbose_name_plural': '3. Foydalanuvchi Yutuqlari',
                'db_table': 'achievements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_file_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='Rasm File ID')),
                ('food_name', models.CharField(max_length=255, verbose_name='Taom nomi')),
                ('weight_g', models.FloatField(default=0.0, verbose_name='Vazn (g)')),
                ('calories', models.FloatField(default=0.0, verbose_name='Kaloriya (kcal)')),
                ('protein_g', models.FloatField(default=0.0, verbose_name='Oqsil (g)')),
                ('fat_g', models.FloatField(default=0.0, verbose_name="Yog' (g)")),
                ('carbs_g', models.FloatField(default=0.0, verbose_name='Uglevod (g)')),
                ('meal_time', models.CharField(default='snack', max_length=50, verbose_name='Vaqt sektori')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': '2. Kiritilgan Taomlar',
                'db_table': 'meals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reminder_time', models.CharField(default='08:00', max_length=10, verbose_name='Eslatish vaqti')),
                ('reminder_type', models.CharField(default='breakfast', max_length=50, verbose_name='Eslatma turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Eslatma',
                'verbose_name_plural': '4. Ovqatlanish Eslatmalari',
                'db_table': 'reminders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq Ismi")),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ismi')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiyasi')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon / ID')),
                ('photo_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='Rasm URL')),
                ('dob', models.CharField(default='2000-01-01', max_length=100, verbose_name="Tug'ilgan sana")),
                ('weight_kg', models.FloatField(blank=True, default=70.0, null=True, verbose_name='Vazn (kg)')),
                ('target_weight_kg', models.FloatField(blank=True, default=65.0, null=True, verbose_name='Maqsadli vazn (kg)')),
                ('height_cm', models.FloatField(blank=True, default=170.0, null=True, verbose_name="Bo'y (cm)")),
                ('age', models.IntegerField(blank=True, default=25, null=True, verbose_name='Yosh')),
                ('gender', models.CharField(blank=True, default='Male', max_length=50, null=True, verbose_name='Jinsi')),
                ('activity_level', models.CharField(blank=True, default='Lightly active', max_length=100, null=True, verbose_name='Faollik')),
                ('diet_preference', models.CharField(blank=True, default='No preference', max_length=100, null=True, verbose_name='Parhez afzalligi')),
                ('daily_goal_kcal', models.FloatField(default=2000.0, verbose_name='Kunlik kaloriya normasi (kcal)')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP Status')),
                ('streak_days', models.IntegerField(default=0, verbose_name='Streak kunlari')),
                ('points', models.IntegerField(default=100, verbose_name='Ballar')),
                ('level', models.IntegerField(default=1, verbose_name='Daraja')),
                ('free_requests_today', models.IntegerField(default=0, verbose_name="Bugungi bepul so'rovlar")),
                ('last_request_date', models.DateField(blank=True, null=True, verbose_name="Oxirgi so'rov sanasi")),
                ('last_streak_date', models.DateField(blank=True, null=True, verbose_name='Oxirgi streak sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqti")),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': '1. Foydalanuvchilar',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Kodi / Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Rejim Nomi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('calories', models.FloatField(default=2000.0, verbose_name='Kaloriya (kcal)')),
                ('protein_g', models.FloatField(default=120.0, verbose_name='Oqsil (g)')),
                ('carbs_g', models.FloatField(default=200.0, verbose_name='Uglevod (g)')),
                ('fat_g', models.FloatField(default=70.0, verbose_name="Yog' (g)")),
                ('goal', models.CharField(default="Sog'lom turmush tarzi", max_length=255, verbose_name='Maqsadi')),
                ('image_url', models.CharField(default='assets/diet_mediterranean.jpg', max_length=512, verbose_name='Rasm URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('is_my_diet', models.BooleanField(default=False, verbose_name="Mening Rejimimda sukut bo'yicha")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
            ],
            options={
                'verbose_name': 'Parhez Rejimi',
                'verbose_name_plural': '5. Parhez Rejimlar',
                'db_table': 'diet_plans',
            },
        ),
    ]
